name: Prod -> Build branch

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-to-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed to push back to the repo

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: |
          npm ci || npm i

      - name: Build
        run: npm run build
        env:
          BASE_PATH: /quantum

      - name: Publish to build branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: build
          folder: build
          clean: true
          commit-message: "Publish build from ${{ github.sha }}"
